In [1]:
import numpy as np
from utils import *

In [2]:
table = np.load("finalStateTable200eps.npy",allow_pickle=True).item()

In [3]:
initState = np.array([0,0,0,0,0,0,0,0,0])

In [4]:
ret,nstate = findBestNextState(initState,1,0,table)
print(nstate)

[0 0 0 1 0 0 0 0 0]


In [5]:
ret,nstate1 = findBestNextState(nstate,-1,0,table)
print(ret)
ret,nstate2 = findBestNextState(nstate1,1,0,table)
print(ret)

print(nstate2)

True
True
[-1  1  0  1  0  0  0  0  0]


In [6]:
ret,nstate3 = findBestNextState(nstate2,-1,0,table)
print(ret)
ret,nstate4 = findBestNextState(nstate3,1,0,table)
print(ret)

print(nstate4)

True
True
[-1  1  0  1  1 -1  0  0  0]


In [7]:
# lets try an optimal game
initState = np.array([0,0,0,0,1,-1,0,0,0])
ret,nstate = findBestNextState(initState,1,0,table)
print(ret,nstate)

True [ 0  0  0  0  1 -1  1  0  0]


In [8]:
# so it can win if I let it win
nstate1 = copy.deepcopy(nstate)
nstate1[3] = -1
ret,nstate2 = findBestNextState(nstate1,1,0,table)
print(ret,nstate2)

True [ 0  0  1 -1  1 -1  1  0  0]


In [9]:
# lets try blocking
nstate1 = copy.deepcopy(nstate)
nstate1[8] = -1
ret,nstate2 = findBestNextState(nstate1,1,0,table)
print(ret,nstate2)

# now its a sure win for it....

True [ 0  0  1  0  1 -1  1  0 -1]


In [10]:
# lets try blocking one square
nstate3 = copy.deepcopy(nstate2)
nstate3[2] = -1
ret,nstate4 = findBestNextState(nstate3,1,0,table)
print(ret,nstate4)

False [ 0  0 -1  0  1 -1  1  0 -1]


In [17]:
# seeing values of first move
states = list(table.values())

for i,state in enumerate(states[0]):
    print(state)
    if i > 11:
        break

[array([0, 0, 0, 0, 0, 0, 0, 0, 0]), 146.29851150000005]
[array([1, 0, 0, 0, 0, 0, 0, 0, 0]), 0.6050000000000001]
[array([0, 1, 0, 0, 0, 0, 0, 0, 0]), 0.6500000000000001]
[array([0, 0, 1, 0, 0, 0, 0, 0, 0]), 0.6500000000000001]
[array([0, 0, 0, 1, 0, 0, 0, 0, 0]), 19.78634500000002]
[array([0, 0, 0, 0, 1, 0, 0, 0, 0]), 0.6550000000000001]
[array([0, 0, 0, 0, 0, 1, 0, 0, 0]), 0.55]
[array([0, 0, 0, 0, 0, 0, 1, 0, 0]), 0.8100000000000003]
[array([0, 0, 0, 0, 0, 0, 0, 1, 0]), 0.7050000000000002]
[array([0, 0, 0, 0, 0, 0, 0, 0, 1]), 0.6000000000000001]
[array([-1,  0,  0,  0,  0,  0,  0,  0,  1]), 0.55]
[array([ 0, -1,  0,  0,  0,  0,  0,  0,  1]), 0.5]
[array([ 0,  0, -1,  0,  0,  0,  0,  0,  1]), 0.55]
