In [5]:
# some_file.py
import sys
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, 'C:\\Users\\supre\\RL\\TicTacToe\\scripts')
sys.path.insert(1, 'C:\\Users\\supre\\RL\\TicTacToe\\stateTables')
from utils import *
import numpy as np

In [7]:
table = np.load("..\\stateTables\\finalStateTableLossPenalty100eps.npy",allow_pickle=True).item()

In [8]:
initState = np.array([0,0,0,0,0,0,0,0,0])

In [9]:
ret,nstate = findBestNextState(initState,1,0,table)
print(nstate)

[0 0 0 0 0 0 1 0 0]


In [10]:
ret,nstate1 = findBestNextState(nstate,-1,0,table)
print(ret)
ret,nstate2 = findBestNextState(nstate1,1,0,table)
print(ret)

print(nstate2)

True
True
[-1  0  1  0  0  0  1  0  0]


In [11]:
ret,nstate3 = findBestNextState(nstate2,-1,0,table)
print(ret)
ret,nstate4 = findBestNextState(nstate3,1,0,table)
print(ret)

print(nstate4)

True
True
[-1  0  1  0  1  0  1  0 -1]


In [12]:
# lets try an optimal game
initState = np.array([0,0,0,0,1,-1,0,0,0])
ret,nstate = findBestNextState(initState,1,0,table)
print(ret,nstate)

True [ 0  0  0  0  1 -1  1  0  0]


In [13]:
# so it can win if I let it win
nstate1 = copy.deepcopy(nstate)
nstate1[3] = -1
ret,nstate2 = findBestNextState(nstate1,1,0,table)
print(ret,nstate2)

True [ 0  0  1 -1  1 -1  1  0  0]


In [15]:
# lets try blocking
nstate1 = copy.deepcopy(nstate)
nstate1[2] = -1
ret,nstate2 = findBestNextState(nstate1,1,0,table)
print(ret,nstate2)



True [ 0  0 -1  0  1 -1  1  1  0]


In [15]:
# lets try blocking one square
nstate3 = copy.deepcopy(nstate2)
nstate3[2] = -1
ret,nstate4 = findBestNextState(nstate3,1,0,table)
print(ret,nstate4)

False [ 1  0 -1  0  1 -1  1  0 -1]
